function [theta, fVal, exitFlag] = apatfit(x)
% [theta, fVal, exitFlag] = apatfit(x) estimates the parameters of the
% Apatosaurus distribution using numerical maximum likelihood.
%
% Author: Wilson Ye Chen <yche5077@uni.sydney.edu.au>
% Date:   November 28, 2015

    % Negative log-likelihood
    fun = @(theta)-loglike(x, theta);
    
    % Initial values for Apatosaurus parameters
    mu0 = mean(x);
    sig0 = std(x);
    theta0 = [mu0, sig0, 8, 0, 0.1, 0.9];
    
    % Optimiser options
    opt = optimset( ...
        'Algorithm', 'interior-point', ...
        'UseParallel', 'never', ...
        'MaxIter', 50000, ...
        'MaxFunEvals', 100000, ...
        'Display', 'off');
    
    % Small positive number
    e = eps(double(1));
    
    % Numerically minimise the negative log-likelihood
    [theta, fVal, exitFlag] = fmincon( ...
        fun, ...
        theta0, ...
        [], [], [], [], ...
        [e, e, 2, -1, e, 0.5], ...
        [inf, inf, 100, 1, inf, 1], ...
        [], ...
        opt);
end

function ll = loglike(x, theta)
    ll = sum(log(apatpdf(x, ...
        theta(1), theta(2), theta(3), theta(4), ...
        theta(5), theta(6))));
end
