function aqua_forejob_tc(dataFile, outFile, nEst, intEst, iStart, iEnd)
% aqua_forejob_tc(dataFile, outFile, nEst, intEst, iStart, iEnd) is the top-
% level function for running the forecasting study of the AQUA-gh-tc model.
% This file should be used as the main file for the Matlab compiler.
%
% Author: Wilson Ye Chen <yche5077@uni.sydney.edu.au>
% Date:   February 12, 2016

    load(dataFile);
    rng('shuffle', 'twister');
    rngState = rng();
    [DFore, Q, var1, var5, score1, score5, s1, s5, ...
        Mn, Sd, w, Theta, AccRate, Mapc, Chain] = ...
        aqua_fore_tc(D, Xi, r, ...
        str2num(nEst), ...
        str2num(intEst), ...
        str2num(iStart), ...
        str2num(iEnd));
    save(outFile, ...
        'rngState', ...
        'DFore', 'Q', 'var1', 'var5', 'score1', 'score5', 's1', 's5', ...
        'Mn', 'Sd', 'w', 'Theta', 'AccRate', 'Mapc', 'Chain');
end
