function ...
    [DFore_j, Q_j, var1_j, var5_j, score1_j, score5_j, Beta1_j, Beta5_j, ...
    Mn_j, Sd_j, w_j, Theta_j, AccRate_j, Mapc_j] = ...
    aqua_joinforejob_v2(dirName)
% [DFore_j, Q_j, var1_j, var5_j, score1_j, score5_j, Beta1_j, Beta5_j, ...
% Mn_j, Sd_j, w_j, Theta_j, AccRate_j, Mapc_j] = aqua_joinforejob_v2(dirName)
% joins the result files in a single directory generated by the forecasting
% jobs. The directory must contain only the result files.
%
% Author: Wilson Ye Chen <yche5077@uni.sydney.edu.au>
% Date:   April 25, 2018

    DFore_j   = [];
    Q_j       = [];
    var1_j    = [];
    var5_j    = [];
    score1_j  = [];
    score5_j  = [];
    Beta1_j   = [];
    Beta5_j   = [];
    Mn_j      = [];
    Sd_j      = [];
    w_j       = [];
    Theta_j   = [];
    AccRate_j = [];
    Mapc_j    = [];

    file = dir(dirName);
    for i = 3:numel(file)
        load([dirName, '/', file(i).name]);
        DFore_j   = [DFore_j; DFore];
        Q_j       = [Q_j; Q];
        var1_j    = [var1_j; var1];
        var5_j    = [var5_j; var5];
        score1_j  = [score1_j; score1];
        score5_j  = [score5_j; score5];
        Beta1_j   = [Beta1_j; Beta1];
        Beta5_j   = [Beta5_j; Beta5];
        Mn_j      = [Mn_j; Mn];
        Sd_j      = [Sd_j; Sd];
        w_j       = [w_j; w];
        Theta_j   = [Theta_j; Theta];
        AccRate_j = [AccRate_j; AccRate];
        Mapc_j    = [Mapc_j; Mapc];
        disp([file(i).name, ' appended.']);
    end
end
